### PR TITLE
Checking if openning output file was sucessful.

### PR DESCRIPTION
**Pull request by aidin36**
Resolves Issue #32
Preventing Segmentation Fault if output file doesn't exists or user
does not have access to it.

### CODE REVIEW

**Comment by lfos** [comment]
Thank you for working on this. I am currently going through old PRs and working with contributors to get them merged.

There are some issues with your patch:

1. Parts of you patch use tabs instead of spaces which breaks indentation.
2. We usually just return `1` on errors. Is there any reason you chose `18`?

**Comment by aidin36** [comment]
2. It's a good practice to return different error numbers in case of different errors. Thus, the caller process can check the status code to find out what error occured. Though, using 18 as magic number like this is not a good practice! The ideal is to have some Macros for different errors.

If you don't want to modify the behavior like this, I will change 18 to 1.

1. Sorry. I will fix that after we decided about the second issue.

**Comment by lfos** [comment]
I agree that it is usually a good idea to return different values such that the caller can handle different errors accordingly. However, in this case, we (you) decided it is the callees responsibility to handle the error (i.e. display the error message) and it suffices to inform the caller about whether everything went fine or not.

**Comment by aidin36** [comment]
Agreed.

Both issues fixed.

**Comment by lfos** [comment]
Merged with some minor whitespace changes, thanks!

**Pull request closed without merging**
